### ISSUE TITLE
Forced subtitles are picked up even when put in the safe extensions

### ISSUE THREAD

**Issue by BernCarney** [caronc/nzbget-tidyit#4] opened 2017-10-04 14:01 UTC
Forced subtitles (ie: en.forced.srt | eng.forced.srt) are flagged to be removed even when put in the safe extensions list as any of the following:
```
.en.forced.srt
*.en.forced.srt
.??.forced.srt
.eng.forced.srt
*.eng.forced.srt
.???.forced.srt
```

**Comment by caronc** [comment] 2017-10-04 14:50
Safe entries are files you create in a directory that just tell the script to flat out ignore it (the processing of the entire directory itself).  It's not quite the effect you're going for.

So if i'm understanding you correctly, in your case: if video is identified as __i.am.a.video.mkv__, you want to also allow __i.am.a.video.en.forced.srt__ (and or other extensions too). A way of identifying _safe-extensions_ as you stated?

This could be a really useful feature! :smile:

**Comment by BernCarney** [comment] 2017-10-04 15:01
Correct! I only grab subtitles for videos where english is not the main
audio language (eng or en.srt) and everything else get's forced subtitles
for any non-english parts (en or eng.forced.srt) so it'd be useful to be
able to put those on a safe list so TidyIt doesn't flag them.

Otherwise, everything works buttery smooth.

Thanks!

**Comment by caronc** [comment] 2017-10-04 17:50
I think giving the user input to also control what is allowed is a great idea!

Just so you know though, and with respect to our example with i.am.a.video.mkv. The following formats are already built into it (to accept):
- i.am.a.video.srt
- i.am.a.video.??.srt

Currently it's the addition of the keyword 'forced' that's giving you trouble right now. I may not get to this issue until the weekend.  But i'll let you know when i'm done and get your feedback before we close up the ticket.

**Comment by BernCarney** [comment] 2017-10-04 20:24
Sounds great. Let me know if there’s anything you need from me. I’ll peak
at the code and see if there is anything I can do in the meantime.

**Comment by caronc** [comment] 2017-10-05 02:40
I had a chance to just quickly peek at the code, and it looks like this feature might already be there (in the version you already had). In your NZBGet settings, you should see an entry that looks like this:
![videoextras](https://user-images.githubusercontent.com/850374/31208308-e763b868-a951-11e7-90e9-3f180e826b61.png)

You should just be able to add your entry to the end of this.  If you're attempting to run this from the command line, then i just added that feature (-**-video-extras** and/or **-x**) to override the defaults (same as those shown in the screenshot)

**Comment by caronc** [comment] 2017-10-13 22:41
Any follow up to this? Did you end up getting it working?

**Comment by BernCarney** [comment] 2017-10-15 01:53
Just tested and it seems to be ignoring the exception for forced subtitles even with the extension in the VideoExtras section. I even tried `.???.forced.srt`, `.eng.forced.srt`, `.*.forced.srt` and none worked.

**Setting in TidyIt**
![image](https://user-images.githubusercontent.com/18447002/31580874-1e3dc0e4-b119-11e7-98cd-b0c372368d0e.png)

**Debug Log**
```
TidyIt: [DEBUG] get_files('/mnt/video/movies/Movie Name (2017)') with 1 filter(s)
TidyIt: [DEBUG] Allowed Movie Name (2017) [1080p].mp4 (regex)
TidyIt: [DEBUG] Planned handling (no alike match): /mnt/video/movies/Movie Name (2017)/Movie Name (2017) [1080p].eng.forced.srt
TidyIt: PREVIEW ONLY: Handle FILE: /mnt/video/movies/Movie Name (2017)/Movie Name (2017) [1080p].eng.forced.srt
```

**Directory Listing**
```shell
user@server:/mnt/tank1/video/movies/Movie Name (2017) # ls
Movie Name (2017) [1080p].eng.forced.srt     Movie Name (2017) [1080p].mp4
```

**Comment by caronc** [comment] 2017-10-17 04:40
You definitely want to use **.???.forced.srt** in your case since you want to identify anything unique after the file name.  I think i found the bug and pushed your change to a _new branch_ we can test from first (no longer the master).

If you wouldn't mind, try fetching an updated copy of **TidyIt.py** from [here](https://github.com/caronc/nzbget-tidyit/archive/4-tidyit-extras.zip).  I was able to replicate your issue, and this new version appears to make things work properly (for me anyway).

Keep me posted how the testing goes for you!

**Comment by BernCarney** [comment] 2017-10-17 05:08
I’ll test it tomorrow evening. Thanks for looking into it and I’ll keep you
updated!

**Comment by caronc** [comment] 2017-11-06 13:04
I hadn't heard back from you in a while, did you get everything working or are you still having issues?

**Comment by BernCarney** [comment] 2017-11-06 16:51
Sorry bout that, things got pretty crazy on my end that last few weeks. I'll test tonight after I get back from work and update.

**Comment by BernCarney** [comment] 2017-11-07 01:47
Still doesn't seem to be working on my end unless I'm reading this wrong. Debug output is as follows. I moved the old plugin into a folder outside the jail so it wouldn't be giving false positives. I also added a more traditional .srt file to check that as well.

```
TidyIt: [DEBUG] get_files('/mnt/video/movies/Name of Movie (2007)') with 1 filter(s)
TidyIt: [DEBUG] Allowed Name of Movie (2007) [Bluray-1080p].mkv (regex)
TidyIt: [DEBUG] Planned handling (no alike match): /mnt/video/movies/Name of Movie (2007)/Name of Movie (2007) [Bluray-1080p].en.forced.srt
TidyIt: [DEBUG] Planned handling (no alike match): /mnt/video/movies/Name of Movie (2007)/Name of Movie (2007) [Bluray-1080p].eng.forced.srt
TidyIt: PREVIEW ONLY: Handle FILE: /mnt/video/movies/Name of Movie (2007)/Name of Movie (2007) [Bluray-1080p].en.forced.srt
TidyIt: PREVIEW ONLY: Handle FILE: /mnt/video/movies/Name of Movie (2007)/Name of Movie (2007) [Bluray-1080p].eng.forced.srt
...
TidyIt: [DEBUG] Exiting with return code: 93
Script TidyIt.py with command DoTidy successful
Close
```

The weird thing is, I have the following folder/files with similar names that aren't being picked up...
```
/mnt/video/movies/Name of OtherMovie (2015)/
/mnt/video/movies/Name of OtherMovie (2015)/Name of OtherMovie (2015) [WEBDL-720p].eng.forced.srt
/mnt/video/movies/Name of OtherMovie (2015)/Name of OtherMovie (2015) [WEBDL-720p].mkv
```

**Comment by caronc** [comment] 2017-11-08 02:21
You can't use the master branch for this test, **you need to take your test copy from the [forked branch](https://github.com/caronc/nzbget-tidyit/archive/4-tidyit-extras.zip)** and _not_ from the master.

When i tested from the command line it worked great:
```bash
# Created a working directory to use
mkdir -p tmp/tvshows/

# placed some dummy files:
dd if=/dev/zero of=tmp/tvshows/mytest.video01.mkv count=1 bs=1024
dd if=/dev/zero of=tmp/tvshows/mytest.video02.mkv count=1 bs=1024

# Now create some variations of files:
dd if=/dev/zero of=tmp/tvshows/mytest.video01.srt count=1 bs=128
dd if=/dev/zero of=tmp/tvshows/mytest.video02.eng.forced.srt count=1 bs=128

# Now run our TidyIt script (turn off age checking) with new VideoExtras
# values set on the command line:
python TidyIt.py -D -m 0  -a 0 --video-extras='.???.forced.srt' tmp
```

Then the output i get is great; specifically:
```
...
2017-11-07 21:15:06,383 - 16243 - DEBUG - mytest.video02.eng.forced.srt belongs to mytest.video02.mkv
2017-11-07 21:15:06,383 - 16243 - DEBUG - mytest.video01.srt belongs to mytest.video01.mkv
...
```

It picks up the .srt file (because that's just built right into the code).  But it also picks up the extras i apply.   Now this _VideoExtras_ flag is also available in NZBGet too, so you can set the value here (you don't have to use the CLI).

**Edit**: ```--video-extras='???.forced.srt'``` should have read ```--video-extras='.???.forced.srt'``` (the period up front to denote the start of the extension)

**Comment by BernCarney** [comment] 2017-11-08 04:15
I did use the test copy from the forked branch. I'll double check but I'm
pretty sure I did.

**Comment by caronc** [comment] 2017-11-08 04:50
Strange, well I'll see what else i can dig up.  I'll try to reproduce this using NZBGet since that appears to be what you're using. Maybe just the CLI works...

Hmm... I'll keep you posted on what i find too.

**Comment by BernCarney** [comment] 2017-11-08 07:10
It's possible that it's the NZBGet interface not passing the configuration
correctly? I'll look into it as well and get back to you.

**Comment by BernCarney** [comment] 2017-11-08 07:14
I stand corrected. It doesn't look like the files were over-written when I cloned the repository. I'll try again and update, sorry for the confusion!

**Comment by BernCarney** [comment] 2017-11-08 07:39
Got the correct version in there and still no luck. I did notice however that my settings were still in NZBGet. I'm wondering if NZBGet  caches scripts and since the name of the directories are the same it's using a cached version of it.

**Comment by caronc** [comment] 2017-11-08 12:28
Your theory is possibly. I also noticed a typo in my last post (I edited it). Maybe this is the issue?

**Comment by caronc** [comment] 2018-01-25 14:29
I hadn't heard back from you in a while.  It's mostly my fault for not following up though.  There is a small update I pushed back in November that allows you to specify these options (and added extras) right from within NZBGet's configuration now too.

So far i'm pretty happy with the changes; they _appear_ to be doing what you asked (for me anyway). I must admit, i'm still a bit stumped that your not sharing the same success.  Be sure you pull from the [forked branch](https://github.com/caronc/nzbget-tidyit/archive/4-tidyit-extras.zip) and _not_ from the master (I realize i'm repeating myself here, but I just want to cover this angle).

At this point: I feel i should merge all of these changes (as a result of this issue you raised) into the master branch this weekend. I'd like to close this issue up for good; but i'd like to do it with you satisfied in the end as well!

**Comment by caronc** [comment] 2018-01-28 18:48
As an update, I've merged everything into the master branch now.

**Comment by caronc** [comment] 2018-02-26 02:24
Thanks again for bringing the bug to my attention; I'm confident it's resolved! I'm closing this ticket for now since i haven't heard back from in in a little over 3 months.  If you have any questions or need me to re-open it just leave a comment and I will.

**Closed as completed by caronc** 2018-02-26 02:24 UTC
Labels: enhancement
